### ISSUE TITLE
Create `raw.datapack` Schema

### ISSUE THREAD

**Issue by OpenJ92** [OpenJ92/starcraft-data-platform#2]
# Create `raw.datapack` Schema

## Description
Design the `raw.datapack` schema in SQL to store metadata for game units and abilities.

## Tasks
- [x] Create the `UNIT_TYPE` table with columns:
- [x] Create the `ABILITY` table with columns:
- [x] Add foreign key relationships:
  - Link abilities to their associated units where applicable.
- [x] Test the schema on a local database.

## Acceptance Criteria
- Schema executes without errors and matches the requirements.

**Comment by OpenJ92** [comment]
> ### **General Observations** from GPT-4o
> - The schema creation is modular and well-organized:
>   - Individual tables (`UNIT_TYPE`, `ABILITY`) are defined in separate `.sql` files.
>   - The `datapack/schema.sql` file collects the table definitions at its level.
>   - The top-level `schema.sql` manages the inclusion of lower-level schemas.
> - The use of comments for explaining the columns and constraints is excellent—it makes the schema easier to understand.
>
> ---
>
> ### **Strengths**
> 1. **Modular Design**:
>    - Each table is in its own file, making it easy to locate and modify specific definitions.
>    - The hierarchical `schema.sql` files at each level ensure modularity and scalability.
>
> 2. **Good Use of Foreign Keys**:
>    - The `ability_unit_type_fkey` constraint in `ABILITY` correctly references `UNIT_TYPE` and includes an `ON DELETE SET NULL` clause, which is appropriate for this use case.
>
> 3. **Documentation**:
>    - The use of inline comments explaining the purpose of each column and constraint is very helpful for future reference and collaboration.
>
> 4. **`CREATE SCHEMA` Safety**:
>    - Including `CREATE SCHEMA IF NOT EXISTS datapack;` in the top-level `raw/schema.sql` ensures that the schema is created only if it doesn't already exist.
>
> ---
>
> ### **Suggestions for Improvement**
> 1. **Add a Schema Prefix to File Names**:
>    - To make it easier to distinguish between files from different schemas, consider prefixing filenames with the schema name:
>      - For example: `datapack.unit_type.sql` and `datapack.ability.sql`.
>
> 2. **Enforce NOT NULL Where Applicable**:
>    - Add `NOT NULL` constraints for columns that are required (e.g., `name`, `release_string`, etc.) to improve data integrity.
>    - Example for `UNIT_TYPE`:
>      ```sql
>      name TEXT NOT NULL,  -- Name of the unit (required)
>      race TEXT NOT NULL   -- Race to which the unit belongs (required)
>      ```
>
> 3. **Index Commonly Queried Columns**:
>    - If `release_string` or `id` is frequently queried in `UNIT_TYPE` or `ABILITY`, consider adding indexes to improve query performance.
>    - Example:
>      ```sql
>      CREATE INDEX idx_unit_type_release ON datapack.UNIT_TYPE (release_string);
>      CREATE INDEX idx_ability_release ON datapack.ABILITY (release_string);
>      ```
>
> 4. **Add an Audit Trail (Optional)**:
>    - If you anticipate needing to track changes or debug data issues, consider adding `created_at` and `updated_at` columns with default timestamps:
>      ```sql
>      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
>      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
>      ```
>
> ---
>
> ### **Summary of Changes**
> 1. **`UNIT_TYPE.sql`**:
>    - Defines the `UNIT_TYPE` table with columns for unit metadata.
> 2. **`ABILITY.sql`**:
>    - Defines the `ABILITY` table with a foreign key to `UNIT_TYPE`.
> 3. **`datapack/schema.sql`**:
>    - Collects and includes `UNIT_TYPE.sql` and `ABILITY.sql`.
> 4. **`raw/schema.sql`**:
>    - Ensures the `datapack` schema exists and includes `datapack/schema.sql`.
> 5. **Top-Level `schema.sql`**:
>    - Calls the `raw/schema.sql` file to initiate schema creation for the `datapack` module.
>
> ---
>
> ### **Acceptance Criteria**
> - [x] Tables are modularized into separate `.sql` files.
> - [x] Foreign key constraints are properly defined with `ON DELETE SET NULL`.
> - [x] Top-level `schema.sql` executes child schema files in the correct order.
> - [x] Comments provide sufficient documentation for understanding the schema.

**Comment by OpenJ92** [comment]
Your suggestions are well taken. Before we close this issue, I'll consider your changes. I've not competed docstrings on the ability table just yet. I need some time to understand what exactly 'Abilities' are.

I should set up GitFlow strategy main->dev->feature-datapack-schema where future changes will be made.

**Comment by OpenJ92** [comment]
Note: I should have API access to GPT-4o with the premium membership. Make a small script that runs `git format-patch origin/main --stdout | gpt-code-review` for output like that above.

**Comment by OpenJ92** [comment]
> > ### **Suggestions for Improvement**
> >      
> >      * For example: `datapack.unit_type.sql` and `datapack.ability.sql`.
> > 2. **Enforce NOT NULL Where Applicable**:
> >    
> >    * Add `NOT NULL` constraints for columns that are required (e.g., `name`, `release_string`, etc.) to improve data integrity.
> >    * Example for `UNIT_TYPE`:
> >      ```sql
> >      name TEXT NOT NULL,  -- Name of the unit (required)
> >      race TEXT NOT NULL   -- Race to which the unit belongs (required)
> >      ```
> > 3. **Index Commonly Queried Columns**:
> >    
> >    * If `release_string` or `id` is frequently queried in `UNIT_TYPE` or `ABILITY`, consider adding indexes to improve query performance.
> >    * Example:
> >      ```sql
> >      CREATE INDEX idx_unit_type_release ON datapack.UNIT_TYPE (release_string);
> >      CREATE INDEX idx_ability_release ON datapack.ABILITY (release_string);
> >      ```
> > 4. **Add an Audit Trail (Optional)**:
> >    
> >    * If you anticipate needing to track changes or debug data issues, consider adding `created_at` and `updated_at` columns with default timestamps:
> >      ```sql
> >      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
> >      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
> >      ```

I'm going to bring these into a new Milestone or Issue for a later date. Until I start ingesting data on a large enough scale and work on analytics views, I wont be able to determine which of these will need implementation. We'll look back at this later.
