### ISSUE TITLE
Create `raw.replay` Schema

### ISSUE THREAD

**Issue by OpenJ92** [OpenJ92/starcraft-data-platform#6]
# Create `raw.replay` Schema

## Description
Design the `raw.replay` schema in SQL to store metadata and contextual information about Starcraft II game replays. This schema will serve as the central layer for replay-specific data, including game details and player mappings.

## Tasks
- [x] Create the following tables:
  - `Info` (general replay metadata)
  - `Player` (player-specific data for each replay)
  - `Team` (team compositions and assignments)
- [x] Define foreign key relationships:
  - Link players to their corresponding replays.
  - Link teams to their replays and players.
- [x] Test the schema on a local database to ensure correctness and referential integrity.

## Acceptance Criteria
- All tables are defined in the `raw.replay` schema.
- Foreign key relationships are implemented correctly.
- Schema executes without errors on a local database.

**Comment by OpenJ92** [comment]
There're columns in the Player table that are unclear to me at the moment. They are the __KILLED__ and __KILLED_BY__ fields. I believe they're other players (Who did they 'defeat' in this game) and so are potentially self referential PLAYER__ID__. 

I have to investigate what they are and decide if they'll be incorporated within the table or if an external table will be needed to capture this information before closing this Issue.

**Comment by OpenJ92** [comment]
I've got a lead on the [columns](https://github.com/GraylinKim/sc2reader/blob/d69feb4e0be597581040588193579d29e8241431/sc2reader/data/__init__.py#L59C1-L69C33) in the sc2reader repository where __Killed__ and __Killed_By__ are defined.

        #: A reference to the player that killed this unit. Only available for 2.0.8+ replays.
        #: This value is not set if the killer is unknown or not relevant (morphed into a
        #: different unit or used to create a building, etc)
        self.killing_player = None


        #: A reference to the unit that killed this unit. Only available for 2.1+ replays.
        #: This value is not set if the killer is unknown or not relevant (morphed into a
        #: different unit or used to create a building, etc). If the killing unit dies before
        #: the killed unit dies, a bug may cause the killing unit to be None. This can occur
        #: due because of projectile speeds.
        self.killing_unit = None
